spring.application.name=Xpay

spring.profiles.active=dev

#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#app.timezone=Africa/Lagos
server.servlet.contextPath=/Xpay/api/v1

server.port=8080
server.use-forward-headers=true