package com.dot.Xpay.service.impl;


import com.dot.Xpay.domain.Transaction;
import com.dot.Xpay.domain.TransactionDailySummary;
import com.dot.Xpay.dto.response.TransactionResponse;
import com.dot.Xpay.dto.response.TransactionSummaryResponse;
import com.dot.Xpay.enums.GenerationMode;
import com.dot.Xpay.enums.TransactionStatus;
import com.dot.Xpay.exception.CustomException;
import com.dot.Xpay.repository.TransactionDailySummaryRepository;
import com.dot.Xpay.repository.TransactionRepository;
import com.dot.Xpay.service.TransactionService;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.Optional;

@Slf4j
@Service
@RequiredArgsConstructor
public class TransactionServiceImpl implements TransactionService {


    private final TransactionRepository transactionRepository;
    private final TransactionDailySummaryRepository dailySummaryRepository;

    @Override
    public Page<TransactionResponse> getTransactions(
            String status,
            String accountNumber,
            LocalDate startDate,
            LocalDate endDate,
            Pageable pageable
    ) {

        validateDateRange(startDate, endDate);

        TransactionStatus txnStatus = parseStatus(status);

        Specification<Transaction> spec = Specification
                .where(TransactionSpecification.hasStatus(txnStatus))
                .and(TransactionSpecification.hasAccount(accountNumber))
                .and(TransactionSpecification.createdBetween(startDate, endDate));

        return transactionRepository.findAll(spec, pageable)
                .map(this::getTransactionResponse);
    }

    @Override
    @Transactional
    public TransactionSummaryResponse generateAndSaveSummary(LocalDate date, GenerationMode mode) {

        Optional<TransactionDailySummary> existing =
                dailySummaryRepository.findBySummaryDate(date);

        // 1. If already generated, return saved summary
        if (existing.isPresent()) {
            TransactionDailySummary saved = existing.get();

            TransactionSummaryResponse summary = new TransactionSummaryResponse();
            summary.setDate(date.toString());
            summary.setTotalTransactions(saved.getTotalTransactions());
            summary.setTotalAmount(saved.getTotalAmount());
            summary.setTotalFees(saved.getTotalFees());
            summary.setTotalCommission(saved.getTotalCommission());

            return summary;
        }

        // 2. Generate new summary from transactions
        ZonedDateTime startOfDay = date.atStartOfDay(ZoneId.systemDefault());
        ZonedDateTime endOfDay = date
                .atTime(23, 59, 59, 999_999_999)
                .atZone(ZoneId.systemDefault());

        TransactionSummaryResponse summary =
                transactionRepository.getTransactionsSummary(startOfDay, endOfDay);

        summary.setDate(date.toString());

        //  Save new summary if generated by the systems background service only
        //  to ensure data consistency and accuracy
        if (mode.equals(GenerationMode.GENERATE_AND_PERSIST))
        {
            try {
                TransactionDailySummary entity = TransactionDailySummary.builder()
                        .summaryDate(date)
                        .totalTransactions(summary.getTotalTransactions())
                        .totalAmount(summary.getTotalAmount())
                        .totalFees(summary.getTotalFees())
                        .totalCommission(summary.getTotalCommission())
                        .build();

                dailySummaryRepository.save(entity);

            } catch (DataIntegrityViolationException ex) {
                log.warn("Daily summary for {} already exists. Skipping insert.", date);
            }
        }

        return summary;
    }



    private TransactionStatus parseStatus(String status) {
        if (status == null || status.isBlank()) {
            return null;
        }

        try {
            return TransactionStatus.valueOf(status.toUpperCase());
        } catch (Exception ex) {
            log.error("An error has occurred:{}", ex.getMessage(), ex);
            throw new CustomException("Invalid transaction status: " + status);
        }
    }

    public TransactionResponse getTransactionResponse(Transaction saved) {
        TransactionResponse transactionResponse = new TransactionResponse();
        transactionResponse.setReference(saved.getReference());
        transactionResponse.setSourceAccount(saved.getSourceAccount());
        transactionResponse.setDestinationAccount(saved.getDestinationAccount());
        transactionResponse.setAmount(saved.getAmount());
        transactionResponse.setTransactionFee(saved.getTransactionFee());
        transactionResponse.setBilledAmount(saved.getBilledAmount());
        transactionResponse.setStatus(saved.getStatus().name());
        transactionResponse.setStatusMessage(saved.getStatus().getMessage());
        transactionResponse.setCommissionWorthy(saved.getCommissionWorthy());
        transactionResponse.setCommission(saved.getCommission());
        transactionResponse.setDescription(saved.getDescription());
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        transactionResponse.setCreatedAt(saved.getCreatedAt() != null ? saved.getCreatedAt().format(dateFormatter) : ZonedDateTime.now().format(dateFormatter));
        return transactionResponse;
    }
    private void validateDateRange(LocalDate startDate, LocalDate endDate) {

        if (startDate != null && endDate != null && startDate.isAfter(endDate)) {
            throw new CustomException("Start date cannot be after end date");
        }
    }

}

